#!/bin/bash
# tomcat          Start/Stop the tomcat server.
# chkconfig: 2345 90 60
# description: Tomcat script by GeoSolutions

export CATALINA_HOME=/opt/tomcat
export CATALINA_BASE=/var/lib/tomcat/mapstore/

prog="Apache Tomcat - MapStore"

USERNAME=tomcat

start() {
       echo -n $"Starting $prog: "
       echo
       su - $USERNAME -s /bin/sh -c "CATALINA_BASE=$CATALINA_BASE $CATALINA_HOME/bin/startup.sh"
       return $?
}

restart() {
       stop
       sleep 5
       start
}

stop() {
       echo -n $"Stopping $prog: "
       echo
       su - $USERNAME -s /bin/sh -c "CATALINA_BASE=$CATALINA_BASE $CATALINA_HOME/bin/shutdown.sh -force"
       return $?
}


case "$1" in
 start)
       start
       ;;
 stop)
       stop
       ;;
 restart)
       restart
       ;;
 *)
       echo $"Usage: $0 {start|stop|restart}"
       exit 1
esac

